export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  appUrl: process.env.APP_URL ?? "http://localhost:3000",
  samlEnabled: process.env.SAML_ENABLED === "true",
  samlEntryPoint: process.env.SAML_ENTRY_POINT ?? "",
  samlIssuer: process.env.SAML_ISSUER ?? "",
  samlCert: process.env.SAML_CERT ?? "",
  sendGridApiKey: process.env.SENDGRID_API_KEY ?? "",
  emailFrom: process.env.EMAIL_FROM ?? "noreply@leavemanagementsystem.com",
};
